name: Test PR
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    name: Laravel ${{ matrix.laravel-versions }} (PHP ${{ matrix.php-versions }})
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.2', '7.3', '7.4', '8.0' ]
        laravel-versions: [ '6.*', '7.*' ]
    uses: matriphe/laravel-md5-hash/.github/workflows/laravel_test.yml@master
    with:
      operating_system: ${{ matrix.operating-system }}
      php_version: ${{ matrix.php-versions }}
      laravel_version: ${{ matrix.laravel-versions }}
