name: Test PR
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check_php_style:
    name: Check PHP code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache php-cs-fixer
        uses: actions/cache@v3
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.os }}-${{ github.repository }}-phpcsfixer-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ github.repository }}-phpcsfixer-

      - name: Run php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --dry-run

  test_laravel_6_7:
    name: Laravel ${{ matrix.laravel-versions }} (PHP ${{ matrix.php-versions }})
    needs:
      - check_php_style
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.2', '7.3', '7.4', '8.0' ]
        laravel-versions: [ '6.*', '7.*' ]
    uses: matriphe/laravel-md5-hash/.github/workflows/laravel_test.yml@master
    with:
      operating_system: ${{ matrix.operating-system }}
      php_version: ${{ matrix.php-versions }}
      laravel_version: ${{ matrix.laravel-versions }}

  test_laravel_8:
    name: Laravel ${{ matrix.laravel-versions }} (PHP ${{ matrix.php-versions }})
    needs:
      - check_php_style
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.3', '7.4', '8.0', '8.1' ]
        laravel-versions: [ '8.*' ]
    uses: matriphe/laravel-md5-hash/.github/workflows/laravel_test.yml@master
    with:
      operating_system: ${{ matrix.operating-system }}
      php_version: ${{ matrix.php-versions }}
      laravel_version: ${{ matrix.laravel-versions }}

  test_laravel_9:
    name: Laravel ${{ matrix.laravel-versions }} (PHP ${{ matrix.php-versions }})
    needs:
      - check_php_style
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '8.0', '8.1' ]
        laravel-versions: [ '9.*' ]
    uses: matriphe/laravel-md5-hash/.github/workflows/laravel_test.yml@master
    with:
      operating_system: ${{ matrix.operating-system }}
      php_version: ${{ matrix.php-versions }}
      laravel_version: ${{ matrix.laravel-versions }}
