name: Test PR
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    name: Laravel ${{ matrix.laravel-versions }} (PHP ${{ matrix.php-versions }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.2', '7.3', '7.4', '8.0' ]
        laravel-versions: [ '6.*', '7.*' ]
    steps:
      - name: Run Laravel Test
        uses: matriphe/laravel-md5-hash/.github/workflows/action.yml@v2
        with:
          os: ${{ runner.os }}
          php: ${{ matrix.php-versions }}
          laravel: ${{ matrix.laravel-versions }}
